name: Deploy omni-convert.js via FTP

on:
  push:
    branches:
      - main          # or the branch where the file is located

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Debug — show file tree
        run: |
          echo '=== repo files ==='
          ls -R .

      - name: FTP deploy (only omni-convert.js)
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server:     ${{ secrets.FTP_HOST }}
          username:   ${{ secrets.FTP_USER }}
          password:   ${{ secrets.FTP_PASS }}
          protocol:   ftps                # or ftp, if FTPS is not available
          port:       ${{ secrets.FTP_PORT }}

          #  What we upload
          local-dir:  src/                # only contents of src/ directory
          #  Where we upload (js/ inside the site)
          server-dir: js/                 # relative path: /www/…/js/

          #  Don't touch anything extra
          dangerous-clean-slate: false

          #  Exclude service files, if they accidentally get in
          exclude: |
            .git*
            .github/**
