# .github/workflows/deploy-core.yml
name: Deploy OmniConvertCore via FTP

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy omni-convert.js via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server:     ${{ secrets.FTP_HOST }}
          username:   ${{ secrets.FTP_USER }}
          password:   ${{ secrets.FTP_PASS }}
          local-dir:  src/                           # ОБЯЗАТЕЛЬНО папка, завершается слэшем
          server-dir: ${{ secrets.FTP_PATH }}/src/   # тоже папка
          exclude: |                                 # исключаем всё…
            **/*                                   
            !omni-convert.js                        # …кроме этого файла
