name: Deploy OmniConvertCore via FTP

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy omni-convert.js via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server:     ${{ secrets.FTP_HOST }}
          username:   ${{ secrets.FTP_USER }}
          password:   ${{ secrets.FTP_PASS }}
          local-dir:  src/omni-convert.js            
          server-dir: ${{ secrets.FTP_PATH }}/src/   
